import 'package:wanzi/tool/RoleEnum.dart';

class SolveList {
  static Map<List<RoleEnum>, List<List<RoleEnum>>> solveList = {
    // 优妮雪哥魔驴咲恋扇子
    [
      RoleEnum.youni,
      RoleEnum.xue,
      RoleEnum.xiangcheng_mofashaonv,
      RoleEnum.xiaolian,
      RoleEnum.ninong
    ]: [
      [
        RoleEnum.xiaolian_xiari,
        RoleEnum.meidong,
        RoleEnum.youjiali,
        RoleEnum.riheli,
        RoleEnum.lima
      ],
      [
        RoleEnum.youni,
        RoleEnum.leimu,
        RoleEnum.xiaolian,
        RoleEnum.ninong,
        RoleEnum.lima
      ]
    ],
    // 优衣真步驴黄骑佩可
    [
      RoleEnum.youyi,
      RoleEnum.zhenbu,
      RoleEnum.xiangcheng,
      RoleEnum.youjiali,
      RoleEnum.peikelimu
    ]: [
      [
        RoleEnum.xiangcheng_mofashaonv,
        RoleEnum.monika,
        RoleEnum.kelisitina,
        RoleEnum.huilizi,
        RoleEnum.lian_xinnian
      ],
      [
        RoleEnum.xiangcheng_mofashaonv,
        RoleEnum.monika,
        RoleEnum.kelisitina,
        RoleEnum.lian,
        RoleEnum.lian_xinnian
      ],
      [
        RoleEnum.lingnai,
        RoleEnum.gongzi_wanshengjie,
        RoleEnum.monika,
        RoleEnum.kelisitina,
        RoleEnum.lian_xinnian
      ]
    ],
    // 星法魅魔雷姆黄骑羊驼
    [
      RoleEnum.chuyin,
      RoleEnum.yixu,
      RoleEnum.leimu,
      RoleEnum.youjiali,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.youni,
        RoleEnum.ninong,
        RoleEnum.youjiali,
        RoleEnum.lian_xinnian,
        RoleEnum.lima
      ],
      [
        RoleEnum.xiaolian_xiari,
        RoleEnum.ninong,
        RoleEnum.youjiali,
        RoleEnum.lian_xinnian,
        RoleEnum.lima
      ],
      [
        RoleEnum.xiaolian_xiari,
        RoleEnum.kekeluo_gongzhu,
        RoleEnum.youjiali,
        RoleEnum.riheli,
        RoleEnum.lima
      ],
    ],
    // 魔驴魅魔黄骑静流羊驼
    [
      RoleEnum.xiangcheng_mofashaonv,
      RoleEnum.yixu,
      RoleEnum.youjiali,
      RoleEnum.jingliu,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.bi,
        RoleEnum.xiangzhi_xiari,
        RoleEnum.kelisitina,
        RoleEnum.zhuxi,
        RoleEnum.lima
      ],
      [
        RoleEnum.bi,
        RoleEnum.xiangcheng_mofashaonv,
        RoleEnum.xiangzhi_xiari,
        RoleEnum.zhuxi,
        RoleEnum.lima
      ],
      [
        RoleEnum.labilisita,
        RoleEnum.xiangzhi_xiari,
        RoleEnum.zhuxi,
        RoleEnum.riheli,
        RoleEnum.lima
      ],
      [
        RoleEnum.xiaolian_xiari,
        RoleEnum.xiangzhi_xiari,
        RoleEnum.youjiali,
        RoleEnum.riheli,
        RoleEnum.lima
      ],
      [
        RoleEnum.youni,
        RoleEnum.xiangzhi_xiari,
        RoleEnum.zhuxi,
        RoleEnum.riheli,
        RoleEnum.kekeluo_xinnian
      ],
    ],
    // 真步魔驴咲恋黄骑羊驼
    [
      RoleEnum.zhenbu,
      RoleEnum.xiangcheng_mofashaonv,
      RoleEnum.xiaolian,
      RoleEnum.youjiali,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.xue,
        RoleEnum.qiange_shengdanjie,
        RoleEnum.xiangzhi_xiari,
        RoleEnum.youjiali,
        RoleEnum.riheli
      ],
      [
        RoleEnum.kekeluo_gongzhu,
        RoleEnum.jingliu,
        RoleEnum.zhuxi,
        RoleEnum.qiunai,
        RoleEnum.kekeluo_xinnian
      ],
      [
        RoleEnum.xiaolian_xiari,
        RoleEnum.riheli,
        RoleEnum.maoyiwei,
        RoleEnum.kekeluo_xinnian,
        RoleEnum.lima
      ],
    ],
    // 魔驴魅魔咲恋静流羊驼
    [
      RoleEnum.xiangcheng_mofashaonv,
      RoleEnum.yixu,
      RoleEnum.xiaolian,
      RoleEnum.jingliu,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.youyi_gongzhu,
        RoleEnum.chuyin,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali,
        RoleEnum.lima
      ],
      [
        RoleEnum.youyi_gongzhu,
        RoleEnum.xiangcheng,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali,
        RoleEnum.lima
      ],
    ],
    // 露娜星法魅魔龙锤羊驼
    [
      RoleEnum.luna,
      RoleEnum.chuyin,
      RoleEnum.yixu,
      RoleEnum.qili,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.youni,
        RoleEnum.xue,
        RoleEnum.linai,
        RoleEnum.ling,
        RoleEnum.meidong
      ],
    ],
    // 魔驴魅魔雷姆黄骑羊驼
    [
      RoleEnum.xiangcheng_mofashaonv,
      RoleEnum.yixu,
      RoleEnum.leimu,
      RoleEnum.youjiali,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.youni,
        RoleEnum.ninong,
        RoleEnum.youjiali,
        RoleEnum.lian_xinnian,
        RoleEnum.lima
      ],
      [
        RoleEnum.xiaolian_xiari,
        RoleEnum.lamu,
        RoleEnum.youjiali,
        RoleEnum.riheli,
        RoleEnum.lima
      ],
      [
        RoleEnum.labilisita,
        RoleEnum.xiaolian,
        RoleEnum.ninong,
        RoleEnum.lin,
        RoleEnum.lima
      ],
    ],
    // 真步驴黄骑静流羊驼
    [
      RoleEnum.zhenbu,
      RoleEnum.xiangcheng,
      RoleEnum.youjiali,
      RoleEnum.jingliu,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.yixu,
        RoleEnum.kekeluo_gongzhu,
        RoleEnum.qiunai
      ],
      [
        RoleEnum.kekeluo_gongzhu,
        RoleEnum.xiangzhi_xiari,
        RoleEnum.zhuxi,
        RoleEnum.riheli,
        RoleEnum.kekeluo_xinnian
      ],
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.yixu,
        RoleEnum.sisihua,
        RoleEnum.lima
      ],
    ],
    // 优衣真步魔驴黄骑鬼裁
    [
      RoleEnum.youyi,
      RoleEnum.zhenbu,
      RoleEnum.xiangcheng_mofashaonv,
      RoleEnum.youjiali,
      RoleEnum.fangxi_wanshengjie
    ]: [
      [
        RoleEnum.kailu_xiari,
        RoleEnum.an,
        RoleEnum.kekeluo_gongzhu,
        RoleEnum.riheli,
        RoleEnum.kekeluo_xinnian
      ],
      [
        RoleEnum.youni,
        RoleEnum.youjiali,
        RoleEnum.riheli,
        RoleEnum.riheli_xinnian,
        RoleEnum.kekeluo_xinnian
      ],
      [
        RoleEnum.xiangcheng_mofashaonv,
        RoleEnum.monika,
        RoleEnum.kelisitina,
        RoleEnum.riheli_xinnian,
        RoleEnum.lian_xinnian
      ],
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.youjiali,
        RoleEnum.kelisitina,
        RoleEnum.riheli
      ],
      [
        RoleEnum.youni,
        RoleEnum.monika,
        RoleEnum.kelisitina,
        RoleEnum.riheli,
        RoleEnum.lian_xinnian
      ],
      [
        RoleEnum.luna,
        RoleEnum.yixu,
        RoleEnum.sisihua,
        RoleEnum.an,
        RoleEnum.kekeluo_gongzhu
      ],
      [
        RoleEnum.luna,
        RoleEnum.lingnai,
        RoleEnum.labilisita,
        RoleEnum.youjiali,
        RoleEnum.kekeluo_xinnian
      ],
      [
        RoleEnum.qiange_shengdanjie,
        RoleEnum.leimu,
        RoleEnum.xiaolian,
        RoleEnum.ninong,
        RoleEnum.lima
      ],
    ],
    // 魔驴咲恋黄骑静流羊驼
    [
      RoleEnum.xiangcheng_mofashaonv,
      RoleEnum.xiaolian,
      RoleEnum.youjiali,
      RoleEnum.jingliu,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali,
        RoleEnum.zhuxi
      ],
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.xiangcheng_mofashaonv,
        RoleEnum.youjiali,
        RoleEnum.zhuxi
      ],
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.lingmei_xinnian,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali
      ],
    ],
    // 魅魔水电雷姆咲恋羊驼
    [
      RoleEnum.yixu,
      RoleEnum.xiaolian_xiari,
      RoleEnum.leimu,
      RoleEnum.xiaolian,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.xiaolian_xiari,
        RoleEnum.lamu,
        RoleEnum.youjiali,
        RoleEnum.riheli,
        RoleEnum.lima
      ],
      [
        RoleEnum.youni,
        RoleEnum.xue,
        RoleEnum.zhenbu,
        RoleEnum.ninong,
        RoleEnum.lima
      ],
      [
        RoleEnum.yixu,
        RoleEnum.linai,
        RoleEnum.xiaolian_xiari,
        RoleEnum.leimu,
        RoleEnum.lima
      ],
      [
        RoleEnum.youni,
        RoleEnum.linai,
        RoleEnum.xiaolian_xiari,
        RoleEnum.shenyue,
        RoleEnum.leimu
      ],
    ],
    // 露娜魅魔咲恋扇子羊驼
    [
      RoleEnum.luna,
      RoleEnum.yixu,
      RoleEnum.xiaolian,
      RoleEnum.ninong,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.xiaolian_xiari,
        RoleEnum.ling,
        RoleEnum.xiaolian,
        RoleEnum.ninong,
        RoleEnum.lima
      ],
      [
        RoleEnum.youni,
        RoleEnum.qiange_shengdanjie,
        RoleEnum.xiangcheng,
        RoleEnum.xiaolian,
        RoleEnum.ninong
      ],
    ],
    // 优衣真步魅魔高达羊驼
    [
      RoleEnum.youni,
      RoleEnum.zhenbu,
      RoleEnum.yixu,
      RoleEnum.peikelimu_gongzhu,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali,
        RoleEnum.zhuxi
      ],
      [
        RoleEnum.xiangcheng_mofashaonv,
        RoleEnum.yixu,
        RoleEnum.sisihua,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali
      ],
      [
        RoleEnum.xiangcheng_mofashaonv,
        RoleEnum.yixu,
        RoleEnum.sisihua,
        RoleEnum.an,
        RoleEnum.youjiali
      ],
    ],
    // 真步咲恋黄骑静流羊驼
    [
      RoleEnum.zhenbu,
      RoleEnum.xiaolian,
      RoleEnum.youjiali,
      RoleEnum.jingliu,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali,
        RoleEnum.riheli
      ],
      [
        RoleEnum.xue,
        RoleEnum.xiaolian_xiari,
        RoleEnum.xiaolian,
        RoleEnum.ninong,
        RoleEnum.lima
      ],
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.xiangcheng_mofashaonv,
        RoleEnum.an,
        RoleEnum.youjiali
      ],
    ],
    // 真步魔驴黄骑静流羊驼
    [
      RoleEnum.zhenbu,
      RoleEnum.xiangcheng_mofashaonv,
      RoleEnum.youjiali,
      RoleEnum.jingliu,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.luna,
        RoleEnum.youjiali,
        RoleEnum.riheli,
        RoleEnum.riheli_xinnian,
        RoleEnum.kekeluo_xinnian
      ],
      [
        RoleEnum.luna,
        RoleEnum.xiangcheng_mofashaonv,
        RoleEnum.yixu,
        RoleEnum.sisihua,
        RoleEnum.lima
      ],
      [
        RoleEnum.kailu_xiari,
        RoleEnum.luna,
        RoleEnum.sisihua,
        RoleEnum.an,
        RoleEnum.lin
      ],
    ],
    // 水电咲恋扇子黄骑羊驼
    [
      RoleEnum.xiaolian_xiari,
      RoleEnum.xiaolian,
      RoleEnum.ninong,
      RoleEnum.youjiali,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali,
        RoleEnum.riheli
      ],
    ],
    // 魔驴伊绪可可萝黄骑羊驼
    [
      RoleEnum.xiangcheng_mofashaonv,
      RoleEnum.yixu,
      RoleEnum.kekeluo,
      RoleEnum.youjiali,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali,
        RoleEnum.jita,
        RoleEnum.riheli,
        RoleEnum.lima
      ],
      [
        RoleEnum.youni,
        RoleEnum.xiaolian_xiari,
        RoleEnum.jita,
        RoleEnum.riheli,
        RoleEnum.lima
      ],
      [
        RoleEnum.xiaolian_xiari,
        RoleEnum.kekeluo_gongzhu,
        RoleEnum.zhuxi,
        RoleEnum.riheli,
        RoleEnum.lima
      ],
      [
        RoleEnum.youni,
        RoleEnum.xiaolian_xiari,
        RoleEnum.kekeluo_gongzhu,
        RoleEnum.riheli,
        RoleEnum.lima
      ],
    ],
    // 星法魔驴水电雷姆羊驼
    [
      RoleEnum.chuyin,
      RoleEnum.xiangcheng_mofashaonv,
      RoleEnum.xiaolian_xiari,
      RoleEnum.leimu,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.chuyin,
        RoleEnum.yixu,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali,
        RoleEnum.lima
      ],
      [
        RoleEnum.youni,
        RoleEnum.xiaolian_xiari,
        RoleEnum.ninong,
        RoleEnum.qili,
        RoleEnum.lima
      ],
    ],
    // 真步魅魔黄骑佩可羊驼
    [
      RoleEnum.zhenbu,
      RoleEnum.yixu,
      RoleEnum.youjiali,
      RoleEnum.peikelimu,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.kekeluo_gongzhu,
        RoleEnum.zhuxi,
        RoleEnum.riheli,
        RoleEnum.fangxi,
        RoleEnum.lian_xinnian
      ],
      [
        RoleEnum.xiaolian_xiari,
        RoleEnum.kekeluo_gongzhu,
        RoleEnum.zhuxi,
        RoleEnum.riheli,
        RoleEnum.fangxi
      ],
      [
        RoleEnum.chuyin,
        RoleEnum.yixu,
        RoleEnum.sisihua,
        RoleEnum.kekeluo_gongzhu,
        RoleEnum.youjiali
      ],
    ],
    // 星法水电雷姆黄骑猫拳
    [
      RoleEnum.chuyin,
      RoleEnum.xiaolian_xiari,
      RoleEnum.leimu,
      RoleEnum.youjiali,
      RoleEnum.riheli
    ]: [
      [
        RoleEnum.chuyin,
        RoleEnum.yixu,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali,
        RoleEnum.lima
      ],
      [
        RoleEnum.youni,
        RoleEnum.xiaolian_xiari,
        RoleEnum.ninong,
        RoleEnum.qili,
        RoleEnum.lima
      ],
    ],
    // 真步伊绪咲恋黄骑羊驼
    [
      RoleEnum.zhenbu,
      RoleEnum.yixu,
      RoleEnum.xiaolian,
      RoleEnum.youjiali,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.chuyin,
        RoleEnum.yixu,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali,
        RoleEnum.zhuxi
      ],
      [
        RoleEnum.chuyin,
        RoleEnum.yixu,
        RoleEnum.xiaolian_xiari,
        RoleEnum.kekeluo_gongzhu,
        RoleEnum.zhuxi
      ],
      [
        RoleEnum.xiaolian,
        RoleEnum.jingliu,
        RoleEnum.zhuxi,
        RoleEnum.qiunai,
        RoleEnum.kekeluo_xinnian
      ],
      [
        RoleEnum.xiaolian_xiari,
        RoleEnum.lamu,
        RoleEnum.xiangzhi_xiari,
        RoleEnum.youjiali,
        RoleEnum.lingyin
      ],
      [
        RoleEnum.xiaolian_xiari,
        RoleEnum.labilisita,
        RoleEnum.zhuxi,
        RoleEnum.kekeluo_xinnian,
        RoleEnum.fangxi_wanshengjie
      ],
      [
        RoleEnum.qiange_shengdanjie,
        RoleEnum.xiaolian_xiari,
        RoleEnum.riheli,
        RoleEnum.riheli_xinnian,
        RoleEnum.kekeluo_xinnian
      ],
      [
        RoleEnum.chuyin,
        RoleEnum.yixu,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali,
        RoleEnum.zhuxi
      ],
      [
        RoleEnum.youni,
        RoleEnum.youjiali,
        RoleEnum.riheli,
        RoleEnum.riheli_xinnian,
        RoleEnum.kekeluo_xinnian
      ],
      [
        RoleEnum.youni,
        RoleEnum.xiaolian_xiari,
        RoleEnum.ninong,
        RoleEnum.riheli,
        RoleEnum.qili
      ],
      [
        RoleEnum.xiaolian_xiari,
        RoleEnum.lamu,
        RoleEnum.xiangzhi_xiari,
        RoleEnum.youjiali,
        RoleEnum.zhenyang_youqibing
      ],
    ],
    // 魔驴伊绪咲恋黄骑鬼裁
    [
      RoleEnum.xiangcheng_mofashaonv,
      RoleEnum.yixu,
      RoleEnum.xiaolian,
      RoleEnum.youjiali,
      RoleEnum.fangxi_wanshengjie
    ]: [
      [
        RoleEnum.chuyin,
        RoleEnum.yixu,
        RoleEnum.sisihua,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali
      ],
      [
        RoleEnum.youni,
        RoleEnum.xue,
        RoleEnum.shenyue,
        RoleEnum.xiaolian,
        RoleEnum.ninong
      ],
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali,
        RoleEnum.qiunai
      ],
      [
        RoleEnum.chuyin,
        RoleEnum.yixu,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali,
        RoleEnum.qiunai
      ],
    ],
    // 魔驴伊绪雷姆咲恋羊驼
    [
      RoleEnum.xiangcheng_mofashaonv,
      RoleEnum.yixu,
      RoleEnum.leimu,
      RoleEnum.xiaolian,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.chuyin,
        RoleEnum.xiaolian_xiari,
        RoleEnum.ninong,
        RoleEnum.riheli,
        RoleEnum.lima
      ],
      [
        RoleEnum.youyi_gongzhu,
        RoleEnum.xiaolian_xiari,
        RoleEnum.ninong,
        RoleEnum.riheli,
        RoleEnum.lima
      ],
      [
        RoleEnum.youyi_gongzhu,
        RoleEnum.xiaolian_xiari,
        RoleEnum.yili,
        RoleEnum.leimu,
        RoleEnum.lima
      ],
    ],
    // 飞田水电雷姆美冬羊驼
    [
      RoleEnum.youyi_gongzhu,
      RoleEnum.xiaolian_xiari,
      RoleEnum.leimu,
      RoleEnum.meidong,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.youyi,
        RoleEnum.zhenbu,
        RoleEnum.yixu,
        RoleEnum.youjiali,
        RoleEnum.fangxi_wanshengjie
      ],
      [
        RoleEnum.youni,
        RoleEnum.xue,
        RoleEnum.xiangcheng,
        RoleEnum.linai,
        RoleEnum.lima
      ],
      [
        RoleEnum.youyi_gongzhu,
        RoleEnum.yixu,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali,
        RoleEnum.qiunai
      ],
    ],
    // 魔驴魅魔咲恋黄骑羊驼
    [
      RoleEnum.xiangcheng_mofashaonv,
      RoleEnum.yixu,
      RoleEnum.xiaolian,
      RoleEnum.youjiali,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.zhenbu,
        RoleEnum.youjiali,
        RoleEnum.jingliu,
        RoleEnum.zhuxi,
        RoleEnum.qiunai
      ],
      [
        RoleEnum.xiaolian,
        RoleEnum.jingliu,
        RoleEnum.lian,
        RoleEnum.zhuxi,
        RoleEnum.lima
      ],
      [
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali,
        RoleEnum.lian,
        RoleEnum.riheli,
        RoleEnum.lima
      ],
    ],
    // 优衣真步魔驴黄骑佩可
    [
      RoleEnum.youyi,
      RoleEnum.zhenbu,
      RoleEnum.xiangcheng_mofashaonv,
      RoleEnum.youjiali,
      RoleEnum.peikelimu
    ]: [
      [
        RoleEnum.bi,
        RoleEnum.gongzi_wanshengjie,
        RoleEnum.monika,
        RoleEnum.kelisitina,
        RoleEnum.lian_xinnian
      ],
      [
        RoleEnum.bi,
        RoleEnum.monika,
        RoleEnum.kelisitina,
        RoleEnum.zhuxi,
        RoleEnum.lian_xinnian
      ],
      [
        RoleEnum.luna,
        RoleEnum.youjiali,
        RoleEnum.riheli,
        RoleEnum.riheli_xinnian,
        RoleEnum.kekeluo_xinnian
      ],
      [
        RoleEnum.youni,
        RoleEnum.kekeluo_gongzhu,
        RoleEnum.zhuxi,
        RoleEnum.riheli,
        RoleEnum.kekeluo_xinnian
      ],
      [
        RoleEnum.xiangcheng_mofashaonv,
        RoleEnum.monika,
        RoleEnum.kelisitina,
        RoleEnum.riheli_xinnian,
        RoleEnum.lian_xinnian
      ],
      [
        RoleEnum.lingnai,
        RoleEnum.monika,
        RoleEnum.kelisitina,
        RoleEnum.zhuxi,
        RoleEnum.lian_xinnian
      ],
    ],
    // 真步伊绪黄骑静流羊驼
    [
      RoleEnum.zhenbu,
      RoleEnum.yixu,
      RoleEnum.youjiali,
      RoleEnum.jingliu,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.labilisita,
        RoleEnum.xiangzhi_xiari,
        RoleEnum.meimei_wanshengjie,
        RoleEnum.zhuxi,
        RoleEnum.kekeluo_xinnian
      ],
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali,
        RoleEnum.riheli
      ],
      [
        RoleEnum.kekeluo_gongzhu,
        RoleEnum.xiangzhi_xiari,
        RoleEnum.zhuxi,
        RoleEnum.riheli,
        RoleEnum.kekeluo_xinnian
      ],
    ],
    // 真步咲恋黄骑真阳羊驼
    [
      RoleEnum.zhenbu,
      RoleEnum.xiaolian,
      RoleEnum.youjiali,
      RoleEnum.zhenyang,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.youni,
        RoleEnum.xue,
        RoleEnum.xiaolian,
        RoleEnum.ninong,
        RoleEnum.lima
      ],
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali,
        RoleEnum.riheli
      ],
    ],
    // 魔驴雷姆黄骑真阳羊驼
    [
      RoleEnum.xiangcheng_mofashaonv,
      RoleEnum.leimu,
      RoleEnum.youjiali,
      RoleEnum.zhenyang,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.xue,
        RoleEnum.shenyue,
        RoleEnum.xiaolian,
        RoleEnum.ninong,
        RoleEnum.lima
      ],
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali,
        RoleEnum.zhuxi
      ],
      [
        RoleEnum.youni,
        RoleEnum.xue,
        RoleEnum.xiaolian,
        RoleEnum.ninong,
        RoleEnum.lima
      ],
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali,
        RoleEnum.qiunai
      ],
    ],
    // 魔驴雷姆咲恋美冬羊驼
    [
      RoleEnum.xiangcheng_mofashaonv,
      RoleEnum.leimu,
      RoleEnum.xiaolian,
      RoleEnum.meidong,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.youni,
        RoleEnum.xue,
        RoleEnum.shenyue,
        RoleEnum.riheli,
        RoleEnum.lima
      ],
      [
        RoleEnum.youyi_gongzhu,
        RoleEnum.chuyin,
        RoleEnum.xiaolian_xiari,
        RoleEnum.riheli,
        RoleEnum.lima
      ],
      [
        RoleEnum.xue,
        RoleEnum.qiange_shengdanjie,
        RoleEnum.leimu,
        RoleEnum.ninong,
        RoleEnum.lima
      ],
    ],
    // 雪哥拉姆咲恋真阳羊驼
    [
      RoleEnum.xue,
      RoleEnum.lamu,
      RoleEnum.xiaolian,
      RoleEnum.zhenyang,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali,
        RoleEnum.riheli
      ],
      [
        RoleEnum.xiaolian_xiari,
        RoleEnum.leimu,
        RoleEnum.xiaolian,
        RoleEnum.ninong,
        RoleEnum.lima
      ],
    ],
    // 魔驴雷姆咲恋真阳羊驼
    [
      RoleEnum.xiangcheng_mofashaonv,
      RoleEnum.leimu,
      RoleEnum.xiaolian,
      RoleEnum.zhenyang,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.youni,
        RoleEnum.xiaolian_xiari,
        RoleEnum.leimu,
        RoleEnum.ninong,
        RoleEnum.lima
      ],
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali,
        RoleEnum.zhuxi
      ],
      [
        RoleEnum.xue,
        RoleEnum.xiangcheng,
        RoleEnum.xiaolian,
        RoleEnum.ninong,
        RoleEnum.lima
      ],
    ],
    // 星法魔驴黄骑静流羊驼
    [
      RoleEnum.chuyin,
      RoleEnum.xiangcheng_mofashaonv,
      RoleEnum.youjiali,
      RoleEnum.jingliu,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.yixu,
        RoleEnum.sisihua,
        RoleEnum.lima
      ],
      [
        RoleEnum.luna,
        RoleEnum.xiangcheng_mofashaonv,
        RoleEnum.yixu,
        RoleEnum.sisihua,
        RoleEnum.lima
      ],
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.xiangcheng_mofashaonv,
        RoleEnum.sisihua,
        RoleEnum.youjiali
      ],
    ],
    // EMT妹法静流江花羊驼
    [
      RoleEnum.aimiliya,
      RoleEnum.qianli,
      RoleEnum.jingliu,
      RoleEnum.konghua_dajianghu,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.labilisita,
        RoleEnum.kekeluo_gongzhu,
        RoleEnum.xiangzhi_xiari,
        RoleEnum.zhuxi,
        RoleEnum.lian_xinnian
      ],
      [
        RoleEnum.xiaolian_xiari,
        RoleEnum.kekeluo_gongzhu,
        RoleEnum.xiangzhi_xiari,
        RoleEnum.zhuxi,
        RoleEnum.kekeluo_xinnian
      ],
    ],
    // 伊绪雷姆咲恋扇子羊驼
    [
      RoleEnum.yixu,
      RoleEnum.leimu,
      RoleEnum.xiaolian,
      RoleEnum.ninong,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali,
        RoleEnum.lian_xinnian
      ],
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali,
        RoleEnum.konghua_dajianghu
      ],
    ],
    // 魔驴伊绪黄骑佩可羊驼
    [
      RoleEnum.xiangcheng_mofashaonv,
      RoleEnum.yixu,
      RoleEnum.youjiali,
      RoleEnum.peikelimu,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.linai,
        RoleEnum.kekeluo_gongzhu,
        RoleEnum.youjiali,
        RoleEnum.riheli,
        RoleEnum.lian_xinnian
      ],
      [
        RoleEnum.youjiali,
        RoleEnum.meimei_wanshengjie,
        RoleEnum.riheli,
        RoleEnum.fangxi,
        RoleEnum.lian_xinnian
      ],
      [
        RoleEnum.youni,
        RoleEnum.qiange_shengdanjie,
        RoleEnum.linai,
        RoleEnum.monika,
        RoleEnum.kekeluo_xinnian
      ],
    ],
    // 雪哥魔驴咲恋扇子羊驼
    [
      RoleEnum.xue,
      RoleEnum.xiangcheng_mofashaonv,
      RoleEnum.xiaolian,
      RoleEnum.ninong,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.xiaolian_xiari,
        RoleEnum.xiangzhi_xiari,
        RoleEnum.youjiali,
        RoleEnum.riheli,
        RoleEnum.lima
      ],
      [
        RoleEnum.xiaolian_xiari,
        RoleEnum.shenyue,
        RoleEnum.xiaolian,
        RoleEnum.ninong,
        RoleEnum.lima
      ],
      [
        RoleEnum.xiaolian_xiari,
        RoleEnum.ling,
        RoleEnum.xiaolian,
        RoleEnum.ninong,
        RoleEnum.lima
      ],
      [
        RoleEnum.zhenbu,
        RoleEnum.youjiali,
        RoleEnum.jingliu,
        RoleEnum.qiunai,
        RoleEnum.lima
      ],
    ],
    // 魔驴雷姆咲恋扇子羊驼
    [
      RoleEnum.xiangcheng_mofashaonv,
      RoleEnum.leimu,
      RoleEnum.xiaolian,
      RoleEnum.ninong,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali,
        RoleEnum.zhuxi
      ],
      [
        RoleEnum.xue,
        RoleEnum.leimu,
        RoleEnum.xiaolian,
        RoleEnum.ninong,
        RoleEnum.lima
      ],
      [
        RoleEnum.leimu,
        RoleEnum.xiaolian,
        RoleEnum.ninong,
        RoleEnum.kekeluo_xinnian,
        RoleEnum.lima
      ],
      [
        RoleEnum.xiaolian_xiari,
        RoleEnum.kekeluo_gongzhu,
        RoleEnum.leimu,
        RoleEnum.ninong,
        RoleEnum.lima
      ],
    ],
    // 真步伊绪美冬静流羊驼
    [
      RoleEnum.zhenbu,
      RoleEnum.yixu,
      RoleEnum.meidong,
      RoleEnum.jingliu,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.luna,
        RoleEnum.yixu,
        RoleEnum.sisihua,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali
      ],
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali,
        RoleEnum.qiunai
      ],
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.xiangcheng_mofashaonv,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali
      ],
    ],
    // 优衣真步伊绪黄骑鬼裁
    [
      RoleEnum.youyi,
      RoleEnum.zhenbu,
      RoleEnum.yixu,
      RoleEnum.youjiali,
      RoleEnum.fangxi_wanshengjie
    ]: [
      [
        RoleEnum.luna,
        RoleEnum.yixu,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali,
        RoleEnum.riheli
      ],
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.yixu,
        RoleEnum.xiaolian,
        RoleEnum.qiunai
      ],
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.yixu,
        RoleEnum.youjiali,
        RoleEnum.qiunai
      ],
      [
        RoleEnum.youni,
        RoleEnum.youjiali,
        RoleEnum.riheli,
        RoleEnum.riheli_xinnian,
        RoleEnum.kekeluo_xinnian
      ],
      [
        RoleEnum.luna,
        RoleEnum.yixu,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali,
        RoleEnum.qiunai
      ],
      [
        RoleEnum.kekeluo_gongzhu,
        RoleEnum.monika,
        RoleEnum.kelisitina,
        RoleEnum.zhuxi,
        RoleEnum.kekeluo_xinnian
      ],
    ],
    // 雪哥魔驴咲恋静流羊驼
    [
      RoleEnum.xue,
      RoleEnum.xiangcheng_mofashaonv,
      RoleEnum.xiaolian,
      RoleEnum.jingliu,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.zhenbu,
        RoleEnum.chuyin,
        RoleEnum.yixu,
        RoleEnum.youjiali,
        RoleEnum.riheli
      ],
      [
        RoleEnum.youyi,
        RoleEnum.zhenbu,
        RoleEnum.yixu,
        RoleEnum.youjiali,
        RoleEnum.qiunai
      ],
      [
        RoleEnum.labilisita,
        RoleEnum.kekeluo_gongzhu,
        RoleEnum.zhuxi,
        RoleEnum.lingyin,
        RoleEnum.kekeluo_xinnian
      ],
    ],
    // 优衣真步伊绪黄骑佩可
    [
      RoleEnum.youyi,
      RoleEnum.zhenbu,
      RoleEnum.yixu,
      RoleEnum.youjiali,
      RoleEnum.peikelimu
    ]: [
      [
        RoleEnum.labilisita,
        RoleEnum.kekeluo_gongzhu,
        RoleEnum.xiangzhi_xiari,
        RoleEnum.zhuxi,
        RoleEnum.fangxi_wanshengjie
      ],
      [
        RoleEnum.qiange_shengdanjie,
        RoleEnum.yixu,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali,
        RoleEnum.riheli
      ],
      [
        RoleEnum.youni,
        RoleEnum.qiange_shengdanjie,
        RoleEnum.linai,
        RoleEnum.monika,
        RoleEnum.kekeluo_xinnian
      ],
    ],
    // 魔驴伊绪咲恋美冬羊驼
    [
      RoleEnum.xiangcheng_mofashaonv,
      RoleEnum.yixu,
      RoleEnum.xiaolian,
      RoleEnum.meidong,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.youni,
        RoleEnum.xue,
        RoleEnum.shenyue,
        RoleEnum.riheli,
        RoleEnum.lima
      ],
      [
        RoleEnum.xue,
        RoleEnum.shenyue,
        RoleEnum.xiaolian,
        RoleEnum.ninong,
        RoleEnum.lima
      ],
      [
        RoleEnum.xiaolian_xiari,
        RoleEnum.ninong,
        RoleEnum.youjiali,
        RoleEnum.riheli,
        RoleEnum.lima
      ],
      [
        RoleEnum.xiaolian_xiari,
        RoleEnum.xiangzhi_xiari,
        RoleEnum.youjiali,
        RoleEnum.riheli,
        RoleEnum.lima
      ],
    ],
    // EMT拉姆静流江花羊驼
    [
      RoleEnum.aimiliya,
      RoleEnum.lamu,
      RoleEnum.jingliu,
      RoleEnum.konghua_dajianghu,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.youni,
        RoleEnum.xiaolian_xiari,
        RoleEnum.zhuxi,
        RoleEnum.riheli,
        RoleEnum.lima
      ],
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.yixu,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali
      ],
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.xiangcheng,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali
      ],
    ],
    // 真步魔驴咲恋扇子羊驼
    [
      RoleEnum.zhenbu,
      RoleEnum.xiangcheng_mofashaonv,
      RoleEnum.xiaolian,
      RoleEnum.ninong,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali,
        RoleEnum.lima
      ],
      [
        RoleEnum.youyi_gongzhu,
        RoleEnum.xiangcheng,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali,
        RoleEnum.lima
      ],
      [
        RoleEnum.youyi_gongzhu,
        RoleEnum.chuyin,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali,
        RoleEnum.lima
      ],
    ],
    // 伊绪水电雷姆妮侬羊驼
    [
      RoleEnum.yixu,
      RoleEnum.xiaolian_xiari,
      RoleEnum.leimu,
      RoleEnum.ninong,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.xiaolian_xiari,
        RoleEnum.lamu,
        RoleEnum.youjiali,
        RoleEnum.riheli,
        RoleEnum.lima
      ],
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali,
        RoleEnum.riheli
      ],
    ],
    // 飞田水电咲恋美冬羊驼
    [
      RoleEnum.youyi_gongzhu,
      RoleEnum.xiaolian_xiari,
      RoleEnum.xiaolian,
      RoleEnum.meidong,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.youni,
        RoleEnum.xue,
        RoleEnum.leimu,
        RoleEnum.ninong,
        RoleEnum.lima
      ],
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.xiaolian_xiari,
        RoleEnum.xiaolian,
        RoleEnum.lima
      ],
    ],
    // 雪哥魔驴咲恋美冬羊驼
    [
      RoleEnum.xue,
      RoleEnum.xiangcheng_mofashaonv,
      RoleEnum.xiaolian,
      RoleEnum.meidong,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.xiaolian_xiari,
        RoleEnum.ninong,
        RoleEnum.youjiali,
        RoleEnum.riheli,
        RoleEnum.lima
      ],
      [
        RoleEnum.kekeluo_gongzhu,
        RoleEnum.xiaolian,
        RoleEnum.riheli,
        RoleEnum.fangxi,
        RoleEnum.lima
      ],
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.xiaolian,
        RoleEnum.riheli,
        RoleEnum.lima
      ],
    ],
    // 雪哥伊绪咲恋黄骑羊驼
    [
      RoleEnum.xue,
      RoleEnum.xiangcheng_mofashaonv,
      RoleEnum.xiaolian,
      RoleEnum.meidong,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.kekeluo_gongzhu,
        RoleEnum.youjiali,
        RoleEnum.zhuxi,
        RoleEnum.riheli,
        RoleEnum.kekeluo_xinnian
      ],
      [
        RoleEnum.youni,
        RoleEnum.xue,
        RoleEnum.qiange,
        RoleEnum.monika,
        RoleEnum.riheli
      ],
    ],
    // 魔驴咲恋黄骑武松秋乃
    [
      RoleEnum.xiangcheng_mofashaonv,
      RoleEnum.xiaolian,
      RoleEnum.youjiali,
      RoleEnum.ling_youqibing,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali,
        RoleEnum.lima
      ],
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali,
        RoleEnum.qiunai
      ],
      [
        RoleEnum.bi,
        RoleEnum.xiaolian_xiari,
        RoleEnum.kelisitina,
        RoleEnum.riheli,
        RoleEnum.lima
      ],
    ],
    // 飞田水电水星真阳羊驼
    [
      RoleEnum.youyi_gongzhu,
      RoleEnum.xiaolian_xiari,
      RoleEnum.chuyin_xiari,
      RoleEnum.zhenyang,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali,
        RoleEnum.zhuxi
      ],
      [
        RoleEnum.ling,
        RoleEnum.meidong,
        RoleEnum.jingliu,
        RoleEnum.peikelimu,
        RoleEnum.lian_xinnian
      ],
    ],
    // 真步魔驴黄骑鬼裁羊驼
    [
      RoleEnum.zhenbu,
      RoleEnum.xiangcheng_mofashaonv,
      RoleEnum.youjiali,
      RoleEnum.fangxi_wanshengjie,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.sisihua,
        RoleEnum.an,
        RoleEnum.youjiali
      ],
      [
        RoleEnum.kekeluo_gongzhu,
        RoleEnum.xiangzhi_xiari,
        RoleEnum.riheli,
        RoleEnum.maoyiwei,
        RoleEnum.lian_xinnian
      ],
      [
        RoleEnum.kailu_xiari,
        RoleEnum.sisihua,
        RoleEnum.an,
        RoleEnum.youjiali,
        RoleEnum.qiunai
      ],
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.an,
        RoleEnum.youjiali,
        RoleEnum.qiunai
      ],
    ],
    // 飞田魔驴咲恋鬼裁羊驼
    [
      RoleEnum.youyi_gongzhu,
      RoleEnum.xiangcheng_mofashaonv,
      RoleEnum.xiaolian,
      RoleEnum.fangxi_wanshengjie,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.youni,
        RoleEnum.xue,
        RoleEnum.xiaolian,
        RoleEnum.ninong,
        RoleEnum.lima
      ],
      [
        RoleEnum.youyi_gongzhu,
        RoleEnum.chuyin,
        RoleEnum.xiangcheng,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali
      ],
      [
        RoleEnum.youyi_gongzhu,
        RoleEnum.chuyin,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali,
        RoleEnum.lima
      ],
    ],
    // 魔驴咲恋美冬黄骑羊驼
    [
      RoleEnum.xiangcheng_mofashaonv,
      RoleEnum.xiaolian,
      RoleEnum.meidong,
      RoleEnum.youjiali,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.xiaolian,
        RoleEnum.kelisitina,
        RoleEnum.jingliu,
        RoleEnum.jiaye,
        RoleEnum.lima
      ],
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.lingmei_xinnian,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali
      ],
      [
        RoleEnum.youni,
        RoleEnum.xue,
        RoleEnum.ling_youqibing,
        RoleEnum.ninong,
        RoleEnum.lima
      ],
      [
        RoleEnum.kekeluo_gongzhu,
        RoleEnum.xiaolian,
        RoleEnum.riheli,
        RoleEnum.fangxi,
        RoleEnum.lima
      ],
    ],
    // 真步咲恋妮侬珠希羊驼
    [
      RoleEnum.zhenbu,
      RoleEnum.xiaolian,
      RoleEnum.ninong,
      RoleEnum.zhuxi,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.xue,
        RoleEnum.qiange,
        RoleEnum.xiaolian_xiari,
        RoleEnum.xiaolian,
        RoleEnum.ninong
      ],
      [
        RoleEnum.xue,
        RoleEnum.xiangcheng,
        RoleEnum.xiaolian_xiari,
        RoleEnum.xiaolian,
        RoleEnum.ninong
      ],
      [
        RoleEnum.shenyue,
        RoleEnum.kekeluo_gongzhu,
        RoleEnum.ling,
        RoleEnum.xiaolian,
        RoleEnum.ninong
      ],
    ],
    // 优衣咲恋黄骑静流羊驼
    [
      RoleEnum.youyi,
      RoleEnum.xiaolian,
      RoleEnum.youjiali,
      RoleEnum.jingliu,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.xiangcheng,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali
      ],
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali,
        RoleEnum.qiunai
      ],
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.xiangcheng_mofashaonv,
        RoleEnum.youjiali,
        RoleEnum.zhuxi
      ],
    ],
    // 露娜伊绪雷姆黄骑佩可
    [
      RoleEnum.luna,
      RoleEnum.yixu,
      RoleEnum.leimu,
      RoleEnum.youjiali,
      RoleEnum.peikelimu
    ]: [
      [
        RoleEnum.youni,
        RoleEnum.linai,
        RoleEnum.xiaolian_xiari,
        RoleEnum.shenyue,
        RoleEnum.qili
      ],
    ],
    // 雪哥魔驴咲恋妮侬鬼裁
    [
      RoleEnum.xue,
      RoleEnum.xiangcheng_mofashaonv,
      RoleEnum.xiaolian,
      RoleEnum.ninong,
      RoleEnum.fangxi_wanshengjie
    ]: [
      [
        RoleEnum.xiaolian_xiari,
        RoleEnum.meidong,
        RoleEnum.youjiali,
        RoleEnum.riheli,
        RoleEnum.lima
      ],
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali,
        RoleEnum.lima
      ],
      [
        RoleEnum.luna,
        RoleEnum.chuyin,
        RoleEnum.xiaolian_xiari,
        RoleEnum.youjiali,
        RoleEnum.qiunai
      ],
    ],
    // 魔驴伊绪可可萝黄骑羊驼
    [
      RoleEnum.xiangcheng_mofashaonv,
      RoleEnum.yixu,
      RoleEnum.kekeluo,
      RoleEnum.youjiali,
      RoleEnum.lima
    ]: [
      [
        RoleEnum.xiaolian_xiari,
        RoleEnum.kekeluo_gongzhu,
        RoleEnum.zhuxi,
        RoleEnum.riheli,
        RoleEnum.lima
      ],
    ],
  };
}
